# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: bouncyquencer

  matrix:
    # MSVC
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: >-
      If ($env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($env:TARGET -eq 'i686-pc-windows-gnu') {
        $env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% &&
      cargo build --target %TARGET% --release &&
      cargo test --target %TARGET% &&
      cargo test --target %TARGET% --release
    )

before_deploy:
  - cargo rustc --target %TARGET% --release --bin %CRATE_NAME% -- -C lto
  - ps: build_scripts\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: n8/QY4EEOrQBBSXhWYuA1J0lFWoubKtJyKtqlKvs1dAvqmi2NyfqpCrvw6/+bxOm 
  description: ''
  on:
    RUST_VERSION: stable
  provider: GitHub

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false

